version: '3.3'

services:

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
  nodered:
    image: nodered/node-red
    ports:
      - 1880:1880

  sensor-emulator:
    container_name: sensor-emulator
    build:
      context: .
    image: sensor-emulator
    environment: 
      - BROKER_URL=mqtt://mosquitto